name: Run Unit Tests

on:
  push:
    branches:
      - master  # Remplace 'main' par 'master'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu pour l'environnement d'exécution
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupérer le code depuis GitHub
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Version .NET que tu utilises
    
    - name: Restore dependencies
      run
