name: Run Unit Tests

on:
  push:
    branches:
      - main  # L'action se déclenche sur chaque push vers la branche 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation d'un environnement Ubuntu (tu peux aussi utiliser windows-latest ou macos-latest)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupère ton code depuis le repository GitHub
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Utilise la version de .NET que tu utilises (modifie si nécessaire)

    - name: Restore dependencies
      run: dotnet restore  # Restaure les dépendances du projet
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal  # Exécute les tests unitaires
