name: Run Unit Tests

on:
  push:
    branches:
      - master  # Remplace 'main' par 'master' ici

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Choisir ubuntu-latest, windows-latest, ou macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupère le code depuis ton repo

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Assure-toi que c'est bien la version de .NET que tu utilises

    - name: Restore dependencies
      run: dotnet restore  # Restaure les dépendances

    - name: Build
      run: dotnet build --no-restore  # Compile le projet sans restaurer les dépendances

    - name: Run tests
      run: dotnet test --no-build --verbosity normal  # Lance les tests
