name: Run Unit Tests

on:
  push:
    branches:
      - master  # Déclenchement de l'action lors des push sur la branche master

jobs:
  test:
    runs-on: ubuntu-latest  # Environnement d'exécution sous Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupérer le code depuis GitHub
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Utilise la version .NET que tu utilises
    
    - name: Restore dependencies
      run: dotnet restore  # Restaurer les dépendances
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal  # Exécuter les tests unitaires
