name: Run Unit Tests

on:
  push:
    branches:
      - master  # Le workflow se déclenche lors de chaque push sur la branche master

jobs:
  test:
    runs-on: ubuntu-latest  # Le workflow s'exécute sur un environnement Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupère le code source depuis le repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Remplace par ta version de .NET si nécessaire

    - name: Restore dependencies
      run: dotnet restore  # Restaure les dépendances .NET

    - name: Build
      run: dotnet build --configuration Release  # Effectue un build (reconstruction du projet)

    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal  # Lance les tests unitaires
